config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  #   sessions: 'users/sessions'
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :surveys do
    resources :pages do
      resources :questions do
        resources :answers
      end
    end

    resources :survey_responses do
      collection do
        get 'thankyou'
      end
    end
  end

  root 'surveys#index'

end

app/views/pages/_form.html.erb
<%= form_with(model: [@survey, @page], local: true) do |form| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pagenum %><br>
    <%= form.number_field :pagenum, class: 'form-control', :required => true %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<div class="py-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Q_id</th>
        <th scope="col">Q_type</th>
        <th scope="col">Description</th>
        <th scope="col">Settings</th>
        <th scope="col" colspan="2">Actions</th>
      </tr>
    </thead>

    <% @page.questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.q_type %></td>
        <td><%= question.description %></td>
        <td><%= question.settings %></td>
        <td><%= link_to 'Edit', edit_survey_page_question_path(@survey, @page, question) %></td>
        <td><%= link_to 'Destroy', survey_page_question_path(@survey, @page, question),
        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to 'New Question', new_survey_page_question_path(@survey, @page) %> |
<%= link_to 'Back', edit_survey_path(@survey) %>

app/views/pages/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Page ID</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.id %></td>
        <td><%= link_to 'Show', [@survey, page] %></td>
        <td><%= link_to 'Destroy', survey_page_path(@survey, page),
        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', edit_survey_path(@survey) %>