config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  #   sessions: 'users/sessions'
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :surveys do
    resources :pages do
      resources :questions do
        resources :answers
      end
    end

    resources :survey_responses do
      collection do
        get 'thankyou'
      end
    end
  end

  root 'surveys#index'

end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id          :bigint(8)        not null, primary key
#  name        :text
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  afterword   :text
#

class Survey < ApplicationRecord
  has_many :pages, dependent: :destroy
  has_many :questions, through: :pages
  has_many :answers, through: :questions
  has_many :responses, class_name: "SurveyResponse", foreign_key: "survey_id", dependent: :destroy
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @ran1 = ''
    @ran2 = ''
    unless params['ran_1'].blank? && params['ran_2'].blank?
      @ran1 = ("%f" % params['ran_1'].gsub(' ','+')).sub(/\.?0*$/, "")
      @ran2 = ("%f" % params['ran_2'].gsub(' ','+')).sub(/\.?0*$/, "")
    end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
    authorize @survey
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    authorize @survey

    if @survey.save
      redirect_to surveys_path
      flash[:success] = 'Survey was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    authorize @survey

    if @survey.update(survey_params)
      redirect_to surveys_path
      flash[:success] = 'Survey was successfully updated.'
    else
      render :edit
    end

  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    authorize @survey
    @survey.destroy

    redirect_to surveys_path
    flash[:success] = 'Survey was successfully destroyed.'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, :description, :afterword)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<!-- needed in surveys/new, survey/edit -->
<%= form_with(model: survey, local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control', :required => true %>
  </div>

  <br>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: 'form-control', rows: 4, :required => true %>
  </div>

  <br>

  <div class="field">
    <%= form.label :afterword %><br>
    <%= form.text_area :afterword, class: 'form-control', rows: 4, :required => true %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/surveys/_question_list.html.erb
<div>
  <%= render @survey.questions %>
</div>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<div class="py-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Page ID</th>
        <th scope="col">Page Number</th>
        <th scope="col" colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @survey.pages.each do |page| %>
        <tr>
          <td><%= page.id %></td>
          <td><%= page.pagenum %></td>
          <td><%= link_to 'Edit', edit_survey_page_path(@survey, page) %></td>
          <td><%= link_to 'Destroy', survey_page_path(@survey, page),
          method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Page', new_survey_page_path(@survey) %> |
<%= link_to 'Back', @survey %>

app/views/surveys/index.html.erb
<div class="py-5 text-center">
  <img class="d-block mx-auto mb-4"
  src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg"
  alt="" width="72" height="72">
  <h1>Surveys</h1>
</div>

<div class="list-group surveys list-group-flush">
  <% @surveys.each do |survey| %>
    <div
      class="list-group-item survey d-flex justify-content-between align-items-center"
      data-redirect="<%= url_for controller: 'surveys', action: 'show', id: survey.id %>"
    >
      <div><%= survey.name %></div>


      <div class="d-flex">
        <button class="btn btn-link fade_button" type="button"
        data-toggle="collapse" data-target="#collapse-<%= survey.id %>"
        aria-expanded="false" aria-controls="collapse-<%= survey.id %>">
          <i class="material-icons">expand_more</i>
        </button>

        <% if user_signed_in? %>
          <%= button_to survey, method: :delete, data: { confirm: 'Are you sure?' },
          class: 'btn btn-link fade_button' do %>
            <i class="material-icons">delete</i>
          <% end %>
        <% end %>
      </div>

    </div>
    <div class="collapse" id="collapse-<%= survey.id %>">
      <div class="card-body"><%= markdown(survey.description) %></div>
    </div>
  <% end %>
</div>

<br>

<% if user_signed_in? %>
  <%= current_user.email %> |
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> |
  <%= link_to 'New Survey', new_survey_path %>
<% end %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<!-- 
<div>
  <h4 class="mb-3">Name:</h4>
  <div class="mb-3"><%= @survey.name %></div>
</div>

<div>
  <h4 class="mb-3">Description:</h4>
  <div class="mb-3"><%= markdown(@survey.description) %></div>
</div>
 -->

<%-# render 'render_question_list', survey: @survey -%>

<br><br>

<form role="form" id="sform" action="<%= survey_survey_responses_path(@survey) %>?ran_1=<%=@ran1%>&ran_2=<%=@ran2%>"
  accept-charset="UTF-8" method="post" id="surveyForm">
  <input type="hidden" name="id" value="<%= @survey.id %>">
  <input type="hidden" name="participant" value="<%= @ran1 + '+' + @ran2 %>">

  <div id="carouselInForm" class="carousel slide" data-interval="false">
    <ol class="carousel-indicators">
      <% @survey.pages.each_with_index do |page, idx| %>
        <% if idx == 0 %>
        <li data-target="#carouselInForm" data-slide-to="<%= idx %>" class="active"></li>
        <% else %>
        <li data-target="#carouselInForm" data-slide-to="<%= idx %>"></li>
        <% end %>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% @survey.pages.each_with_index do |page, idx| %>
        <% if idx == 0 %>
        <div class="carousel-item active">
        <% else %>
        <div class="carousel-item">
        <% end %>
          <%= render page.questions %>
        </div>
      <% end %>
    </div>
    <div class="text-center" id="submit-container">
      <input id="submit_btn" type="submit" value="Submit" class="btn btn-primary"
      data-disable_with="Submitting..."/>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <div>
      <button type="button" class="btn btn-light nav-btn" href="#carouselInForm"
      role="button" data-slide="prev">
        <i class="material-icons">navigate_before</i>
      </button>
    </div>

    <!-- <div id="pagenum" class="text-center py-2"></div> -->

    <div>
      <button type="button" class="btn btn-light nav-btn" href="#carouselInForm"
      role="button" data-slide="next">
        <i class="material-icons">navigate_next</i>
      </button>
    </div>
  </div>
</form>

<style>
  .material-icons {
    vertical-align: middle;
  }
  .nav-btn {
      transition: background .3s;
      background-color: #007dff;
      color: #fff;
      padding: 7px 16px;
      margin-bottom: 10px;
  }
  .nav-btn:hover {
    background: #0071e6;
    color: #fff;
  }
</style>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_survey_path(@survey) %> |
<% end %>
<%= link_to 'Exit', surveys_path, id:"exitLink" %>

<% content_for :scripts do %>
  <script>
  // var pagenumField = document.querySelector('#pagenum');
  //
  // pagenumField.appendChild(document.createTextNode($('.active').index()+1));
  //
  // $('#carouselInForm').on('slide.bs.carousel', function(e){
  //   // console.log(e.direction)     // The direction in which the carousel is sliding (either "left" or "right").
  //   // console.log(e.relatedTarget) // The DOM element that is being slid into place as the active item.
  //   // console.log(e.from)          // The index of the current item.
  //   // console.log(e.to)            // The index of the next item.
  //   pagenumField.firstChild.nodeValue = e.to+1;
  // });
  //
  // var form = document.getElementById('surveyForm');
  //
  // var validateForm = function (){
  //   if (!form.checkValidity()){
  //   }
  // }
  var submitContainer = $('#submit-container');
  var prevBtn = $('[data-slide="prev"]');
  var nextBtn = $('[data-slide="next"]');
  var carouselIndicators = $('.carousel-indicators');

  prevBtn.hide();
  submitContainer.hide();

  if (<%= @survey.pages.length %> === 1) {
    nextBtn.hide();
    carouselIndicators.hide();
    submitContainer.show();
  }

  var validator = $('form').validate({
    showErrors: function (errorMap, errorList) {
      $.each(this.successList, function (index, element) {
        return $(element).popover("dispose");
      });

      $.each(errorList, function (index, error) {
        var ele = $(error.element);
        // if (ele.hasClass('game-input')) return true;
        
        //Instead of referencing the popover directly, I use the element that is the target for the popover

        ele.popover({
          trigger: "manual",
          placement: "top",
          content: error.message,
        });
        
        return ele.popover("show");
      });
    }
  });

  var checkActivePageValidity = function () {
    var activePage = document.querySelector('.carousel-item.active');
    var allValid = ['input', 'textarea', 'select']
      .flatMap(x => Array.from(activePage.querySelectorAll(x)))
      .reduce((allValid, el) => allValid && validator.element($(el)), true);
    return allValid;
  }

  $('form').on('submit', function(e) {
    var isValid = checkActivePageValidity();
    if (!isValid) {
      e.preventDefault();
      return false;
    }
  });

  $('#carouselInForm').on('slide.bs.carousel', function (e) {
    var isActivePageValid = checkActivePageValidity();
    if (!isActivePageValid) {
      e.preventDefault();
      return false;
    }
    if (e.to === <%= @survey.pages.length - 1 %>) {
      prevBtn.show();
      nextBtn.hide();
      submitContainer.show();
    } else if (e.to === 0) {
      prevBtn.hide();
      nextBtn.show();
      submitContainer.hide();
    } else {
      prevBtn.show();
      nextBtn.show();
      submitContainer.hide();
    }
  });
  </script>
<% end %>