config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # , controllers: {
  #   sessions: 'users/sessions'
  # }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :surveys do
    resources :pages do
      resources :questions do
        resources :answers
      end
    end

    resources :survey_responses do
      collection do
        get 'thankyou'
      end
    end
  end

  root 'surveys#index'

end

app/controllers/survey_responses_controller.rb
class SurveyResponsesController < ApplicationController
  before_action :set_survey

  def index
    @responses = @survey.responses.all
        
    respond_to do |format|
      format.html
      format.json  { render :json => @responses.to_json(:include => :answers) }
    end
  end

  def create
    answers = []
    params["answers"].each do |question_id, answer_description|
      question = Question.find(question_id)
      # TODO: Check if answer has any data associated with it
      if params.has_key?('qid') && question_id == params["qid"]
        answer_description += params['q1']+'; '+params['q2']+'; '+params['q3']+'; '+params['q4']
      end
      @answer = Answer.create(description: answer_description)
      question.answers << @answer
      answers << @answer
    end
    @survey_response = SurveyResponse.new(response_params)
    @survey_response.answers << answers
    # Fail if you can't
    if @survey_response.save
      ran1 = ''
      ran2 = ''
      unless params['ran_1'].blank? && params['ran_2'].blank?
        ran1 = params['ran_1']
        ran2 = params['ran_2']
      end
      redirect_to thankyou_survey_survey_responses_path(@survey, :ran1 => ran1, :ran2 => ran2)
      flash[:success] = 'Survey response was successfully created.'
    else
      render :new
    end
  end

  private
    def set_survey
      @survey = Survey.find(params[:survey_id])
    end

    def response_params
      tparams = params.permit(:participant)
      tparams[:survey] = @survey
      tparams
    end
end

app/helpers/survey_responses_helper.rb
module SurveyResponsesHelper
end

app/views/survey_responses/index.html.erb
<h1>Listing All Responses</h1>

<% @responses.each do |response| %>
  <h4>Response <%= response.id %></h4>
  <ul>
    <% response.answers.each do |answer| %>
      <li>
        <div>Participant: <%= response.participant %></div>
        <div>Q_id: <%= answer.question.id %></div>
        <div><%= answer.description %></div>
        <div><%= answer.data %></div>
       </li>
    <% end %>
  </ul>
<% end %>

app/views/survey_responses/thankyou.html.erb
<div class="py-5 text-center">
    <img class="d-block mx-auto mb-4"
    src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg"
    alt="" width="72" height="72">
    <h2>Your response has been recorded. Thank you!</h2>
    <h3>Redirecting you to the second part of the survey...</h3>
    <p class="lead"><%= @survey.afterword %></p>
    <%= link_to 'Home', surveys_path %>
</div>

<% content_for :scripts do %>
<script>
    function findGetParameter(parameterName) {
        var result = null,
            tmp = [];
        var items = location.search.substr(1).split("&");
        for (var index = 0; index < items.length; index++) {
            tmp = items[index].split("=");
            if (tmp[0] === parameterName) result = decodeURIComponent(tmp[1]);
        }
        return result;
    }
    $(function() {
        setTimeout(function() {
            var qstr = "?ran_1="+findGetParameter("ran1")+"&ran_2="+findGetParameter("ran2")
            window.location.href = 'https://ucisocsci.az1.qualtrics.com/jfe/form/SV_9N7BS0ylSNdwbIN'+qstr
        }, 3000);
    });
</script>
<% end %>